name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        env:
          GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: GITHUB_SERVER_URL,GITHUB_REPOSITORY,GITHUB_REF_NAME
          script: |
            set -e

            APP_DIR="${{ secrets.SERVER_WORKING_DIRECTORY }}"
            BRANCH="$GITHUB_REF_NAME"
            REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"

            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            if [ ! -d ".git" ]; then
              echo "Repository not found. Cloning..."
              git clone -b "$BRANCH" "$REPO_URL" .
            else
              echo "Repository exists. Updating..."
              git fetch origin
              git reset --hard "origin/$BRANCH"
              git clean -fd
            fi

            cd docker
            docker compose down || true
            
            # ===== BACKUP DATABASE =====
            echo "Creating deployment backup..."
  
            DB_DIR="../../db-files"
            BACKUP_DIR="../../db-files/backups"
            
            mkdir -p "$BACKUP_DIR"
            
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
            DB_FILE="$DB_DIR/edol-hub-db.mv.db"
            
            if [ -f "$DB_FILE" ]; then
            BACKUP_FILE="$BACKUP_DIR/edol-hub-db_$TIMESTAMP.mv.db"
          
            echo "Creating database backup:"
            echo "$BACKUP_FILE"
          
            cp "$DB_FILE" "$BACKUP_FILE"
            else
            echo "Database file not found. Skipping backup."
            fi
            
            # Remove old backups, keep latest 20
            ls -1t "$BACKUP_DIR"/edol-hub-db_*.mv.db | tail -n +21 | xargs -r rm --
            
            echo "Backup completed."
            # ==========================
  
            docker compose up --build -d