----------------------------------------------------------------------------
-- Reference Data
----------------------------------------------------------------------------

CREATE TABLE material_types
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),

    CONSTRAINT pk_material_types
        PRIMARY KEY (id),
    CONSTRAINT uk_material_types_name
        UNIQUE (name)

);


CREATE TABLE vendors
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY,
    name    varchar(255),
    website varchar(255),

    CONSTRAINT pk_vendors
        PRIMARY KEY (id),
    CONSTRAINT uk_vendors_name
        UNIQUE (name)
);


CREATE TABLE maintenance_definition
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    name           varchar(255),
    description    varchar(2000),
    interval_days  integer,
    interval_hours integer,
    active         boolean NOT NULL,

    CONSTRAINT pk_maintenance_definition
        PRIMARY KEY (id)
);


----------------------------------------------------------------------------
-- Inventory
----------------------------------------------------------------------------

CREATE TABLE filaments
(
    id                             bigint GENERATED BY DEFAULT AS IDENTITY,
    default_empty_spool_weight     double precision,
    default_weight_total           double precision,
    diameter                       double precision,
    recommended_drying_hours       integer,
    recommended_drying_temperature integer,
    material_type_id               bigint NOT NULL,
    vendor_id                      bigint NOT NULL,
    comment                        varchar(2000),
    brand                          varchar(255),
    color_hex                      varchar(255),
    color_name                     varchar(255),
    full_id                        varchar(255),
    printer_filament_profile_id    varchar(255),

    CONSTRAINT pk_filaments
        PRIMARY KEY (id),
    CONSTRAINT fk_filaments_material_type
        FOREIGN KEY (material_type_id)
            REFERENCES material_types (id),
    CONSTRAINT fk_filaments_vendor
        FOREIGN KEY (vendor_id)
            REFERENCES vendors (id)
);

CREATE INDEX idx_filaments_vendor
    ON filaments (vendor_id);

CREATE INDEX idx_filaments_material_type
    ON filaments (material_type_id);


CREATE TABLE filament_spools
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    empty_spool_weight double precision,
    price              numeric(38, 2),
    weight_remaining   double precision,
    weight_total       double precision,
    filament_id        bigint NOT NULL,
    last_dried_at      timestamp,
    last_used_at       timestamp,
    opened_at          timestamp,
    purchased_at       timestamp,
    comment            varchar(2000),
    status             varchar(255)
        CONSTRAINT filament_spools_status_check
            CHECK (
                status IN (
                           'SEALED',
                           'ACTIVE',
                           'EMPTY',
                           'ARCHIVED'
                    )
                ),
    store_url          varchar(255),

    CONSTRAINT pk_filament_spools
        PRIMARY KEY (id),
    CONSTRAINT fk_filament_spools_filament
        FOREIGN KEY (filament_id)
            REFERENCES filaments (id)
);

CREATE INDEX idx_filament_spools_filament
    ON filament_spools (filament_id);


----------------------------------------------------------------------------
-- Printing
----------------------------------------------------------------------------

CREATE TABLE print_jobs
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    file_name        varchar(255),
    task_name        varchar(255),
    current_layer    integer,
    printer_id       integer NOT NULL,
    progress         integer,
    remaining_time   integer,
    total_layers     integer,
    finished_at      timestamp,
    started_at       timestamp,
    plate_image_type varchar(255),
    session_id       varchar(255),
    status           varchar(255)
        CONSTRAINT print_jobs_status_check
            CHECK (
                status IN (
                           'STARTED',
                           'RUNNING',
                           'FINISHED',
                           'FAILED',
                           'CANCELLED'
                    )
                ),
    plate_image      bytea,

    CONSTRAINT pk_print_jobs
        PRIMARY KEY (id)
);


CREATE TABLE job_spool_usage
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    cost              numeric(38, 2),
    used_grams        double precision,
    created_at        timestamp,
    filament_spool_id bigint NOT NULL,
    print_job_id      bigint NOT NULL,

    CONSTRAINT pk_job_spool_usage
        PRIMARY KEY (id),
    CONSTRAINT fk_job_spool_usage_filament_spool
        FOREIGN KEY (filament_spool_id)
            REFERENCES filament_spools (id),
    CONSTRAINT fk_job_spool_usage_print_job
        FOREIGN KEY (print_job_id)
            REFERENCES print_jobs (id)
);

CREATE INDEX idx_job_spool_usage_print_job
    ON job_spool_usage (print_job_id);

CREATE INDEX idx_job_spool_usage_filament_spool
    ON job_spool_usage (filament_spool_id);


CREATE TABLE print_allocation_preview
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    finalized    boolean,
    print_job_id bigint NOT NULL,

    CONSTRAINT pk_print_allocation_preview
        PRIMARY KEY (id),
    CONSTRAINT uk_print_allocation_preview_print_job
        UNIQUE (print_job_id),
    CONSTRAINT fk_print_allocation_preview_print_job
        FOREIGN KEY (print_job_id)
            REFERENCES print_jobs (id)

);


CREATE TABLE print_allocation_group
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    allocated_grams double precision,
    ams_slot        integer,
    missing_grams   double precision,
    requested_grams double precision,
    user_overridden boolean,
    filament_id     bigint,
    preview_id      bigint NOT NULL,
    status          varchar(255)
        CONSTRAINT print_allocation_group_status_check
            CHECK (
                status IN (
                           'RESOLVED',
                           'PARTIAL',
                           'MISSING_SPOOL',
                           'REQUIRES_USER_ACTION',
                           'FINALIZED'
                    )
                ),

    CONSTRAINT pk_print_allocation_group
        PRIMARY KEY (id),
    CONSTRAINT fk_print_allocation_group_filament
        FOREIGN KEY (filament_id)
            REFERENCES filaments (id),
    CONSTRAINT fk_print_allocation_group_preview
        FOREIGN KEY (preview_id)
            REFERENCES print_allocation_preview (id)
);

CREATE INDEX idx_print_allocation_group_preview
    ON print_allocation_group (preview_id);

CREATE INDEX idx_print_allocation_group_filament
    ON print_allocation_group (filament_id);


CREATE TABLE print_allocation_item
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    allocated_grams   double precision,
    estimated_cost    numeric(38, 2),
    user_selected     boolean,
    filament_spool_id bigint,
    group_id          bigint NOT NULL,

    CONSTRAINT pk_print_allocation_item
        PRIMARY KEY (id),
    CONSTRAINT fk_print_allocation_item_filament_spool
        FOREIGN KEY (filament_spool_id)
            REFERENCES filament_spools (id),
    CONSTRAINT fk_print_allocation_item_group
        FOREIGN KEY (group_id)
            REFERENCES print_allocation_group (id)
);

CREATE INDEX idx_print_allocation_item_group
    ON print_allocation_item (group_id);

CREATE INDEX idx_print_allocation_item_filament_spool
    ON print_allocation_item (filament_spool_id);


CREATE TABLE maintenance_execution
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    printer_total_hours integer,
    executed_at         timestamp,
    notes               varchar(255),
    maintenance_id      bigint NOT NULL,

    CONSTRAINT pk_maintenance_execution
        PRIMARY KEY (id),
    CONSTRAINT fk_maintenance_execution_definition
        FOREIGN KEY (maintenance_id)
            REFERENCES maintenance_definition (id)

);

CREATE INDEX idx_maintenance_execution_definition
    ON maintenance_execution (maintenance_id);


CREATE TABLE printer_stats
(
    id                            bigint GENERATED BY DEFAULT AS IDENTITY,
    printer_started_printing_date timestamp,
    total_filament_used_grams     bigint,
    total_jobs                    bigint,
    total_print_seconds           bigint,
    updated_at                    timestamp,

    CONSTRAINT pk_printer_stats
        PRIMARY KEY (id)
);