name: edol

services:
  edolcore:
    build:
      context: ..
      dockerfile: docker/edol-core.Dockerfile
    container_name: edol-core
    environment:
      TZ: Europe/Kyiv
    env_file:
      - ../../.env_edol_core
    depends_on:
      mqtt:
        condition: service_healthy
    ports:
      - "8091:8080"
    volumes:
      - ../../db-files:/app/db-files
      - ../../models:/app/models
      - ../../camera_snapshots:/app/camera_snapshots
      - ../../logs:/app/logs
    restart: unless-stopped

  edolhub:
    build:
      context: ..
      dockerfile: docker/edol-hub.Dockerfile
    container_name: edol-hub
    environment:
      TZ: Europe/Kyiv
    env_file:
      - ../../.env_edol_hub
    depends_on:
      mqtt:
        condition: service_healthy
    ports:
      - "8090:8090"
    volumes:
      - ../../db-files:/app/db-files
      - ../../logs:/app/logs
    restart: unless-stopped

  edolnotify:
    build:
      context: ..
      dockerfile: docker/edol-notify.Dockerfile
    container_name: edol-notify
    environment:
      TZ: Europe/Kyiv
    env_file:
      - ../../.env_edol_notify
    depends_on:
      mqtt:
        condition: service_healthy
    volumes:
      - ../../logs:/app/logs
      - ../../camera_snapshots:/app/camera_snapshots
    restart: unless-stopped

  edolams:
    build:
      context: ..
      dockerfile: docker/edol-ams.Dockerfile
    container_name: edol-ams
    environment:
      TZ: Europe/Kyiv
    env_file:
      - ../../.env_edol_ams
    depends_on:
      mqtt:
        condition: service_healthy
    ports:
      - "8099:8099"
    volumes:
      - ../../logs:/app/logs
    restart: unless-stopped

  mqtt:
    image: emqx/nanomq:latest
    container_name: nanomq
    healthcheck:
      test: [ "CMD", "nanomq", "--help" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped