rules = [
  {"permit": "allow", "username": "edolcore-events", "action": "publish", "topics": ["edolcore/#"]},
  {"permit": "allow", "username": "edolhub-secure", "action": "subscribe", "topics": ["edolcore/#"]},
  {"permit": "deny", "username": "#", "action": "pubsub", "topics": ["#"]}
]
