spring:
  security:
    oauth2:
      client:
        registration:
          edol-keycloak:
            client-id: edol-hub-web
            client-secret: ${EDOL_HUB_WEB_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
          edol-hub-service:
            client-id: ${EDOL_HUB_SERVICE_CLIENT_ID:edol-hub-service}
            client-secret: ${EDOL_HUB_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: edol-keycloak
            scope: tenant.context,core.printer.read,core.printer.manage,core.state.read,core.command.execute,core.media.read
        provider:
          edol-keycloak:
            issuer-uri: ${EDOL_KEYCLOAK_ISSUER_URI}

edol-hub:
  ams-compatibility:
    legacy-tenant-id: ${EDOL_HUB_AMS_COMPATIBILITY_LEGACY_TENANT_ID:}
    ingress-token: ${EDOL_HUB_AMS_COMPATIBILITY_INGRESS_TOKEN:}
